version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "America/Bogota"
    open-pull-requests-limit: 2
    groups:
      python-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/frontend-react"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:15"
      timezone: "America/Bogota"
    open-pull-requests-limit: 2
    groups:
      frontend-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:30"
      timezone: "America/Bogota"
    open-pull-requests-limit: 2
    groups:
      github-actions:
        patterns:
          - "*"
